export const CHAT_CONNECT         = 'CHAT_CONNECT'
export const CHAT_DISCONNECT      = 'CHAT_DISCONNECT'
export const CHAT_SEND_MESSAGE    = 'CHAT_SEND_MESSAGE'
export const CHAT_RECEIVE_MESSAGE = 'CHAT_RECEIVE_MESSAGE'
